apiVersion: apps/v1
kind: Deployment
metadata:
  name: facility-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facility
  template:
    metadata:
      labels:
        app: facility
    spec:
      containers:
      - name: facility
        image: facility-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: postgres-secret
        env:
        - name: DB_HOST
          value: postgres
