apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request
  template:
    metadata:
      labels:
        app: request
    spec:
      containers:
      - name: request
        image: request-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: postgres-secret
        env:
        - name: DB_HOST
          value: postgres
