apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing
  template:
    metadata:
      labels:
        app: routing
    spec:
      containers:
      - name: routing
        image: routing-service:3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
